baseURL: "https://javaman.net/"
languageCode: "en-us"
title: "Gabriel Pizarro"
googleAnalytics: "G-RVP58Z33V4"
permalinks:
    post: "/posts/:slug/"
    page: "/:slug/"
module:
    imports:
        - path: "github.com/CaiJimmy/hugo-theme-stack/v3"
          disable: false
params:
    dateFormat:
        published: "Jan 02, 2006"
        lastUpdated: "Jan 02, 2006 15:04 MST"
    footer:
        since: 2022
    sidebar:
        avatar:
            enabled: true
            local: true
            src: "images/profile.jpg"
        subtitle: "Self-taught. Engages in tomfoolery."
    article:
        readingTime: true
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: "categories"
              params:
                  limit: 10
            - type: "tag-cloud"
              params:
                  limit: 10
        page:
            - type: "toc"
menu:
    social:
        - identifier: "github"
          url: "https://github.com/TheNewJavaman"
          params:
              icon: "brand-github"
          weight: 1
        - identifier: "linkedin"
          url: "https://www.linkedin.com/in/gkpizarro/"
          params:
              icon: "brand-linkedin"
          weight: 2
        - identifier: "patreon"
          url: "https://www.patreon.com/gpizarro"
          params:
              icon: "brand-patreon"
          weight: 3
related:
    includeNewer: true